---
- name: Restart daily backend API services
  hosts: api
  sudo: True
  vars:
    pipeline_phase: "integ"
    component: "daily_backend_api"
    sumologic_logs: "{{ sumologic_logs_defaults_backend_redis }}"
    people_api_datadog_event_deployment_priority: "low"
    datadog_process_checks:
      - "{{ datadog_process_checks_global_defaults }}"
    datadog_event_deployment_priority: "normal" 

  tasks:
    - include_vars: group_vars/main.yml
    
    - name: Stop daily {{ appcore_artifact_id }}
      service: >
        name="{{ appcore_artifact_id }}"
        state=stopped

    - name: Start Daily_api {{ appcore_artifact_id }}
      service: >
        name="{{ appcore_artifact_id }}"
        state=restarted
