---

- name: Deploying people's backend DATA server
  hosts: data
  sudo: True
  vars:
    pipeline_phase: "integ"
    component: "people_data"
    sumologic_logs: "{{ sumologic_logs_defaults_backend_redis }}"
    people_api_datadog_event_deployment_priority: "low"
    datadog_process_checks:
      - "{{ datadog_process_checks_global_defaults }}"
    datadog_event_deployment_priority: "normal"

  tasks:
    - include_vars: group_vars/main.yml

    - name: create required directories
      file: >
        state=directory
        path={{ item }}
        owner={{ jive_user }}
        group={{ jive_group }}
        mode=0755
      with_items:
          - "{{ people_data_backend_service_home }}"
          - "{{ people_data_identity_sync_service_home }}"
          - "{{ people_data_configuration_service_home }}"

    - name: copy upstart init scripts
      template: >
        src=templates/upstart-init.conf.j2
        dest=/etc/init/{{ item.artifact_id }}.conf
        owner=root
        group=root
        mode=755
      with_items:
        - { artifact_id: "{{ people_data_configuration_service_artifact_id }}",
            home: "{{ people_data_configuration_service_home }}",
            artifact: "{{ people_data_configuration_service_artifact }}",
            port: "{{ people_data_configuration_service_manage_port }}",
            startup_timeout: "{{ people_data_configuration_service_startup_timeout }}" }
        - { artifact_id: "{{ people_data_backend_service_artifact_id }}",
            home: "{{ people_data_backend_service_home }}",
            artifact: "{{ people_data_backend_service_artifact }}",
            port: "{{ people_data_backend_service_manage_port }}",
            startup_timeout: "{{ people_data_backend_service_startup_timeout }}" }
        - { artifact_id: "{{ people_data_identity_sync_service_artifact_id }}",
            home: "{{ people_data_identity_sync_service_home }}",
            artifact: "{{ people_data_identity_sync_service_artifact }}",
            port: "{{ people_data_identity_sync_service_manage_port }}",
            startup_timeout: "{{ people_data_identity_sync_service_startup_timeout }}" }


    - name: fetch people configuration-service from nexus
      get_url: >
        url={{ people_data_configuration_service_artifact_url }}
        dest={{ jive_incoming_folder }}/{{ people_data_configuration_service_artifact_name }}
        mode=0755

    - name: fetch people backend-service from nexus
      get_url: >
        url={{ people_data_backend_service_artifact_url }}
        dest={{ jive_incoming_folder }}/{{ people_data_backend_service_artifact_name }}
        mode=0755

    - name: fetch people identity-sync-service from nexus
      get_url: >
        url={{ people_data_identity_sync_service_artifact_url }}
        dest={{ jive_incoming_folder }}/{{ people_data_identity_sync_service_artifact_name }}
        mode=0755

    - name: deploy people configuration-service
      command: mv {{ jive_incoming_folder }}/{{ people_data_configuration_service_artifact_name}} {{ people_data_configuration_service_artifact }}

    - name: deploy people backend
      command: mv {{ jive_incoming_folder }}/{{ people_data_backend_service_artifact_name }} {{ people_data_backend_service_artifact }}

    - name: deploy people identity
      command: mv {{ jive_incoming_folder }}/{{ people_data_identity_sync_service_artifact_name }} {{ people_data_identity_sync_service_artifact }}
